export const categoryMapOldToNew = {
  1: "ZAFEtsbS_twu60cJPh8mY", //FABRYCZNY
  2: "DwNLVj_Mf-bHgSzsL1KZL", //KONWERSJA
  3: "XKBYwLwfXn_Emv8E1hztm", //KONWERSJA SZTYWNY TYŁ
  4: "in1KQgvIjIC1bmV0hBOZd", //KONWERSJA SZTYWNY HUB TYŁ
  5: "in1KQgvIjIC1bmV0hBOZd", //LEKKA KONWERSJA HUB TYŁ
  6: "in1KQgvIjIC1bmV0hBOZd", //HYBRYDA HUB TYŁ
  7: "Vno_VCgCqeoT6XVNXmBo1", //CRUISER HUB TYŁ
  8: "1mkxGiFObWo1Jz2yYtT1Q", //KONWERSJA SZTYWNY HUB PRZÓD
  9: "1mkxGiFObWo1Jz2yYtT1Q", //LEKKA KONWERSJA HUB PRZÓD
  10: "1mkxGiFObWo1Jz2yYtT1Q", //HYBRYDA HUB PRZÓD
  11: "hL96Qxppk34N_4lAU6nPZ", //CRUISER HUB PRZÓD
  12: "hL96Qxppk56N_4lAU6nPZ", //KONWERSJA SZTYWNY MID
  13: "hL96Qxppk56N_4lAU6nPZ", //LEKKA KONWERSJA MID
  14: "hL96Qxppk56N_4lAU6nPZ", //HYBRYDA MID
  15: "vdn0glY4OxzyMAROdDRnK", //KONWERSJA FULL
  16: "DDwqfomYcMsHwEVEgkpE4", //KONWERSJA FULL HUB TYŁ
  17: "DDwqfomYcMsHwEVEgkpE4", //LEKKI FULL HUB TYŁ
  18: "DDwqfomYcMsHwEVEgkpE4", //HYBRYDA FULL HUB TYŁ
  19: "DDwqfomYcMsHwEVEgkpE4", //SZALONA HYBRYDA FULL HUB TYŁ
  20: "ZCaoFYRpohPFZDPPaxI9B", //KONWERSJA FULL HUB PRZÓD
  21: "ZCaoFYRpohPFZDPPaxI9B", //LEKKI FULL HUB PRZÓD
  22: "ZCaoFYRpohPFZDPPaxI9B", //HYBRYDA FULL HUB PRZÓD
  23: "W9mxgnMZbSsp-s8HzAR1U", //KONWERSJA FULL MID
  24: "W9mxgnMZbSsp-s8HzAR1U", //LEKKA KONWERSJA FULL MID
  25: "W9mxgnMZbSsp-s8HzAR1U", //HYBRYDA FULL MID
};
